# Generated by Django 4.0.5 on 2022-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('descripcion', models.TextField()),
                ('nombre', models.BooleanField(default=False)),
            ],
        ),
    ]
